version: "3.9"

services:
  web:
    build: .
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/library_backend_development
    ports:
      - "3000:80"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: library_backend_development
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
